apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
  namespace: dte-cg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliapp
  template:
    metadata:
      labels:
        app: cliapp
    spec:
      containers:
      - name: cliapp
        command:
        - sh
        - -c
        - sleep 6000
        image: amazon/aws-cli
        imagePullPolicy: Always
