apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: dte
  name: dte

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: logdir-permission
  name: logdir-permission
  namespace: dte
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: logdir-permission
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: logdir-permission
    spec:
      containers:
      - args:
        - -c
        - mkdir -p /data/logs && chmod o+rwx /data/logs && exec tail -f /dev/null
        command:
        - sh
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: logdir-permission
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-dir
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data
          type: ""
        name: data-dir
